on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - run: yarn install

      - name: Publish
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: yarn publish:prerelease
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
