on:
  push:
    tags:
      - '**'
  release:
    types:
      - created

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - run: npm install

      - name: Publish
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: npm run publish:prerelease
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
